name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile main application
        run: g++ -std=c++17 -o CarService src/main.cpp

      - name: Compile tests
        run: g++ -std=c++17 -o CarServiceTests tests/main.cpp

      - name: Run tests
        run: ./CarServiceTests
