name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install necessary tools
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Compile the main application
      - name: Compile main application
        run: g++ -std=c++17 -o CarService src/main.cpp src/Semaphore.cpp src/CarStation.cpp

      # Step 4: Compile the tests
      - name: Compile tests
        run: g++ -std=c++17 -o CarServiceTests tests/main.cpp src/Semaphore.cpp src/CarStation.cpp

      # Step 5: Run the tests
      - name: Run tests
        run: ./CarServiceTests
